---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Ubuntu updates
  apt:
    upgrade: dist

- name: Install system administration tools
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - emacs-nox
    - htop
    - httpie
    - unzip

- name: Install VirtualBox Guest Additions
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - virtualbox-guest-dkms
    - virtualbox-guest-utils

- name: Add Docker repository key
  apt_key:
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    keyserver: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  register: add_repository_key

- name: Install prerequisite packages for Docker repository
  apt:
    name: apt-transport-https
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release|lower }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install Docker
  apt:
    name: "docker-ce"

- name: Configure passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Create gbadmin user
  user:
    name: gbadmin
    comment: GhostBox Admin
    group: sudo

- name: Add public ssh key for gbadmin user
  authorized_key:
    user: gbadmin
    state: present
    key: "{{ lookup('file', '../config/gbadmin.key.pub') }}"

- include_tasks: prometheus.yml
