- name: Install Prometheus node exporter
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v0.16.0/node_exporter-0.16.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
