version: 2
jobs:
  build:
    environment:
      - GOPATH: /go
      - GOBIN: /go/bin
    docker:
      - image: circleci/golang:1.10.0
    steps:
      - checkout
      - run: go env
      - run: go install github.com/tangentspace/ghostbox/cmd/boxctl
      - run: ls -lh ${GOBIN}
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
